services:
  dev_db:
    image: postgres:16
    environment:
      - POSTGRES_DB=nestauth_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecret
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  postgres_data:
